/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelbookingsystem;

import hotel.model.*;
import hotel.dao.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hanin
 */
public class admin_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form admin_dashboard
     */
    private javax.swing.JComboBox<String> cmbAvailable;
    private boolean editingExisting = false;
    private int editingRoomId = -1;
    private javax.swing.JButton editBookingBtn;
    private javax.swing.JButton cancelBookingBtn;
    private javax.swing.JButton deleteBookingBtn;
    private javax.swing.JButton pickRoomBtn;
    private boolean suppressRoomNumListener = false;
    // Statistics tab
    private javax.swing.JLabel statTotalRooms, statAvailable, statBooked;
    private javax.swing.JLabel statBookings, statRevenue, statCustomers;

    public admin_dashboard() {
        initComponents();
        wrapWithHeader();   // inject header bar above TabbedPane
        customizeUI();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // full-screen
        setMinimumSize(new java.awt.Dimension(750, 500));
        setResizable(true);
        loadRooms();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RoomNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbRoomType = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        isAvalibleTxt = new javax.swing.JTextField();
        AddRoom = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRooms = new javax.swing.JTable();
        Back = new javax.swing.JButton();
        quit = new javax.swing.JButton();
        price1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewTable = new javax.swing.JTable();
        showBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        Back1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setForeground(new java.awt.Color(161, 101, 58));
        jTabbedPane1.setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Room Number :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 43));

        RoomNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(RoomNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 93, 43));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Type : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 43));

        cmbRoomType.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        cmbRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple" }));
        jPanel1.add(cmbRoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 96, 43));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Is Avilabel :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 43));

        isAvalibleTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(isAvalibleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 104, 43));

        AddRoom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AddRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelbookingsystem/icons8-add-new-32.png"))); // NOI18N
        AddRoom.setText("Add Room");
        AddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRoomActionPerformed(evt);
            }
        });
        jPanel1.add(AddRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 322, 166, 42));

        tblRooms.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblRooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Number", "Type", "Price "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblRooms.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblRoomsPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblRooms);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 96, 410, 207));

        Back.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelbookingsystem/icons8-go-back-24.png"))); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 321, 166, 42));

        quit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        quit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelbookingsystem/icons8-exit-48.png"))); // NOI18N
        quit.setText("Quit");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        jPanel1.add(quit, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 382, 166, 42));

        price1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 104, 43));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Price : ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 43));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelbookingsystem/WhatsApp Image 2026-05-05 at 7.59.37 PM.jpeg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 490));

        jTabbedPane1.addTab("Manage Rooms", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Number", "Room Type", "Price", "Is avalible"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(viewTable);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 690, 220));

        showBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelbookingsystem/icons8-show-property-32.png"))); // NOI18N
        showBtn.setText("Show");
        showBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBtnActionPerformed(evt);
            }
        });
        jPanel2.add(showBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 253, 224, 50));

        exitBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelbookingsystem/icons8-exit-48.png"))); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel2.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 389, 224, 52));

        Back1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelbookingsystem/icons8-go-back-24.png"))); // NOI18N
        Back1.setText("Back");
        Back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back1ActionPerformed(evt);
            }
        });
        jPanel2.add(Back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 321, 224, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelbookingsystem/WhatsApp Image 2026-05-05 at 7.59.37 PM.jpeg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        jTabbedPane1.addTab("View Bookings", jPanel2);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelbookingsystem/WhatsApp Image 2026-05-05 at 7.59.37 PM.jpeg"))); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 490, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Statistics", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new IndexPage().setVisible(true);


    }//GEN-LAST:event_BackActionPerformed

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(null, "Do You Really Want to Exit",
                "Select", JOptionPane.YES_NO_OPTION);

        if (exit == 0) {
            System.exit(0);
        }

    }//GEN-LAST:event_quitActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(null, "Do You Really Want to Exit",
                "Select", JOptionPane.YES_NO_OPTION);

        if (exit == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    private void Back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new IndexPage().setVisible(true);
    }//GEN-LAST:event_Back1ActionPerformed

    private void showBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBtnActionPerformed
        new javax.swing.SwingWorker<java.util.List<Object[]>, Void>() {
            @Override
            protected java.util.List<Object[]> doInBackground() throws Exception {
                return new BookingDAO().getAllBookingsDetailed();
            }
            @Override
            protected void done() {
                try {
                    java.util.List<Object[]> bookings = get();
                    String[] cols = {"ID", "Customer Name", "Room No.", "Type",
                                     "Check-In", "Check-Out", "Nights", "Amount ($)", "Status", "RoomID", "Price"};
                    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(cols, 0) {
                        public boolean isCellEditable(int r, int c) { return false; }
                    };
                    viewTable.setModel(model);

                    for (Object[] row : bookings) {
                        long nights = calcNights((String) row[4], (String) row[5]);
                        model.addRow(new Object[]{
                            row[0], row[1], row[2], row[3], row[4], row[5],
                            nights > 0 ? String.valueOf(nights) : "—", row[6], row[7], row[8], row[9]
                        });
                    }

                    // Widen important columns
                    viewTable.getColumnModel().getColumn(1).setPreferredWidth(140);
                    viewTable.getColumnModel().getColumn(4).setPreferredWidth(85);
                    viewTable.getColumnModel().getColumn(5).setPreferredWidth(85);
                    viewTable.getColumnModel().getColumn(6).setPreferredWidth(55);

                    // Re-apply styles and renderers since the model replacement drops them
                    styleTable(viewTable);

                    // Hide RoomID (9) and Price (10) helper columns after styling
                    for (int ci : new int[]{9, 10}) {
                        viewTable.getColumnModel().getColumn(ci).setMinWidth(0);
                        viewTable.getColumnModel().getColumn(ci).setMaxWidth(0);
                        viewTable.getColumnModel().getColumn(ci).setWidth(0);
                    }

                    if (bookings.isEmpty()) {
                        JOptionPane.showMessageDialog(admin_dashboard.this,
                            "No bookings found.", "Info", JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(admin_dashboard.this,
                        "Error loading bookings: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }.execute();
    }//GEN-LAST:event_showBtnActionPerformed

    private void AddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRoomActionPerformed
        String roomNumber = RoomNumber.getText().trim();
        String type       = cmbRoomType.getSelectedItem().toString();
        String priceStr   = price1.getText().trim();
        String availStr   = cmbAvailable.getSelectedItem().toString();

        if (roomNumber.isEmpty() || priceStr.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Room number and price are required.",
                "Missing Fields", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            boolean available = availStr.equalsIgnoreCase("Yes");
            RoomDAO roomDAO   = new RoomDAO();

            if (editingExisting && editingRoomId > 0) {
                // Update existing room — type, price, and availability
                double price = Double.parseDouble(priceStr);
                if (roomDAO.updateRoom(editingRoomId, type, price, available)) {
                    JOptionPane.showMessageDialog(this,
                        "Room " + roomNumber + " updated successfully!",
                        "Success", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this,
                        "Failed to update room.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                // Add brand-new room
                double price = Double.parseDouble(priceStr);
                Room room = new Room(0, roomNumber, type, price, available);
                if (roomDAO.addRoom(room)) {
                    JOptionPane.showMessageDialog(this,
                        "Room added successfully!",
                        "Success", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this,
                        "Failed to add room.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            // Reset form
            RoomNumber.setText("");
            price1.setText("");
            cmbAvailable.setSelectedIndex(0);
            editingExisting = false;
            editingRoomId   = -1;
            AddRoom.setText("Add Room");
            loadRooms();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                "Please enter a valid number for price.",
                "Invalid Input", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                "Error: " + ex.getMessage(),
                "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AddRoomActionPerformed

    private void tblRoomsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblRoomsPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tblRoomsPropertyChange

    private void customizeUI() {
        java.awt.Font labelFont = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16);
        java.awt.Color white = java.awt.Color.WHITE;

        // Labels - white bold text visible on wood background
        jLabel1.setFont(labelFont); jLabel1.setForeground(white);
        jLabel2.setFont(labelFont); jLabel2.setForeground(white);
        jLabel7.setFont(labelFont); jLabel7.setForeground(white);
        jLabel3.setFont(labelFont); jLabel3.setForeground(white);
        jLabel3.setText("Available :");

        // Text fields
        styleTextField(RoomNumber);
        styleTextField(price1);
        isAvalibleTxt.setVisible(false);

        // Replace isAvalibleTxt with Yes/No combo
        cmbAvailable = new javax.swing.JComboBox<>(new String[]{"Yes", "No"});
        cmbAvailable.setBackground(java.awt.Color.WHITE);
        cmbAvailable.setForeground(new java.awt.Color(40, 40, 40));
        cmbAvailable.setFont(new java.awt.Font("Segoe UI", 0, 15));
        jPanel1.add(cmbAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 130, 38));
        jPanel1.setComponentZOrder(cmbAvailable, 0);

        // Room type combo — add Suite which was missing from generated model
        cmbRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(
            new String[]{"Single", "Double", "Triple", "Suite"}));
        cmbRoomType.setBackground(java.awt.Color.WHITE);
        cmbRoomType.setForeground(new java.awt.Color(40, 40, 40));
        cmbRoomType.setFont(new java.awt.Font("Segoe UI", 0, 15));

        // Buttons
        styleButton(AddRoom, new java.awt.Color(46, 125, 50));
        styleButton(Back,    new java.awt.Color(25, 118, 210));
        styleButton(quit,    new java.awt.Color(198, 40, 40));
        styleButton(showBtn, new java.awt.Color(25, 118, 210));
        styleButton(exitBtn, new java.awt.Color(198, 40, 40));
        styleButton(Back1,   new java.awt.Color(25, 118, 210));

        // View Bookings tab — Edit / Cancel / Delete booking buttons
        editBookingBtn   = new javax.swing.JButton("Edit Booking");
        cancelBookingBtn = new javax.swing.JButton("Cancel Booking");
        deleteBookingBtn = new javax.swing.JButton("Delete Booking");

        styleButton(editBookingBtn,   new java.awt.Color(230, 130, 20));
        styleButton(cancelBookingBtn, new java.awt.Color(156, 39, 176));
        styleButton(deleteBookingBtn, new java.awt.Color(198, 40, 40));

        jPanel2.add(editBookingBtn,   new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 253, 218, 50));
        jPanel2.add(cancelBookingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 313, 218, 50));
        jPanel2.add(deleteBookingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 381, 218, 50));

        editBookingBtn.addActionListener(e -> editSelectedBooking());
        cancelBookingBtn.addActionListener(e -> cancelSelectedBooking());
        deleteBookingBtn.addActionListener(e -> deleteSelectedBooking());

        javax.swing.JButton printInvoiceBtn = new javax.swing.JButton("Print Invoice (PDF)");
        styleButton(printInvoiceBtn, new java.awt.Color(46, 125, 50));
        printInvoiceBtn.addActionListener(e -> printSelectedInvoice());

        jPanel2.revalidate();
        jPanel2.repaint();

        // Tabbed pane
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));

        // Tables
        styleTable(tblRooms);
        styleTable(viewTable);

        // RoomNumber: editable for new rooms; typing resets edit-mode
        RoomNumber.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void changedUpdate(javax.swing.event.DocumentEvent e) { onRoomNumChanged(); }
            public void removeUpdate (javax.swing.event.DocumentEvent e) { onRoomNumChanged(); }
            public void insertUpdate (javax.swing.event.DocumentEvent e) { onRoomNumChanged(); }
        });

        // "Pick Room" button — sits between Add Room and Back
        pickRoomBtn = new javax.swing.JButton("Pick Room");
        styleButton(pickRoomBtn, new java.awt.Color(100, 60, 20));
        jPanel1.add(pickRoomBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 321, 130, 42));
        pickRoomBtn.addActionListener(e -> openRoomPicker());

        // Refactor jPanel1 (Manage Rooms) to be responsive
        jPanel1.removeAll();
        jPanel1.setLayout(new java.awt.BorderLayout(20, 20));
        jPanel1.setBackground(new java.awt.Color(245, 238, 228));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

        javax.swing.JPanel formPanel = new javax.swing.JPanel(new java.awt.GridLayout(4, 2, 10, 25));
        formPanel.setBackground(new java.awt.Color(245, 238, 228));
        jLabel1.setForeground(new java.awt.Color(60, 35, 10));
        jLabel2.setForeground(new java.awt.Color(60, 35, 10));
        jLabel7.setForeground(new java.awt.Color(60, 35, 10));
        jLabel3.setForeground(new java.awt.Color(60, 35, 10));
        formPanel.add(jLabel1); formPanel.add(RoomNumber);
        formPanel.add(jLabel2); formPanel.add(cmbRoomType);
        formPanel.add(jLabel7); formPanel.add(price1);
        formPanel.add(jLabel3); formPanel.add(cmbAvailable);

        javax.swing.JPanel leftPanel = new javax.swing.JPanel(new java.awt.BorderLayout(0, 20));
        leftPanel.setBackground(new java.awt.Color(245, 238, 228));
        leftPanel.add(formPanel, java.awt.BorderLayout.NORTH);

        javax.swing.JPanel p1Btns = new javax.swing.JPanel(new java.awt.GridLayout(4, 1, 10, 15));
        p1Btns.setBackground(new java.awt.Color(245, 238, 228));
        p1Btns.add(AddRoom);
        p1Btns.add(pickRoomBtn);
        p1Btns.add(Back);
        p1Btns.add(quit);
        leftPanel.add(p1Btns, java.awt.BorderLayout.SOUTH);

        jPanel1.add(leftPanel, java.awt.BorderLayout.WEST);
        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        // Refactor jPanel2 (View Bookings) to be responsive
        jPanel2.removeAll();
        jPanel2.setLayout(new java.awt.BorderLayout(15, 15));
        jPanel2.setBackground(new java.awt.Color(245, 238, 228));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

        javax.swing.JPanel p2Btns = new javax.swing.JPanel(new java.awt.GridLayout(2, 1, 0, 10));
        p2Btns.setBackground(new java.awt.Color(245, 238, 228));

        javax.swing.JPanel row1 = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 0));
        row1.setBackground(new java.awt.Color(245, 238, 228));
        row1.add(showBtn);
        row1.add(editBookingBtn);
        row1.add(cancelBookingBtn);
        row1.add(deleteBookingBtn);

        javax.swing.JPanel row2 = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 0));
        row2.setBackground(new java.awt.Color(245, 238, 228));
        row2.add(printInvoiceBtn);
        row2.add(Back1);
        row2.add(exitBtn);

        p2Btns.add(row1);
        p2Btns.add(row2);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);
        jPanel2.add(p2Btns, java.awt.BorderLayout.SOUTH);

        jPanel1.revalidate();
        jPanel1.repaint();
        jPanel2.revalidate();
        jPanel2.repaint();

        setupStatisticsTab();
    }

    // ── HEADER BAR injected above TabbedPane ─────────────────────────────
    private void wrapWithHeader() {
        // Remove the tabbedPane from AbsoluteLayout content pane
        getContentPane().remove(jTabbedPane1);

        // Build header panel
        javax.swing.JPanel header = new javax.swing.JPanel(new java.awt.BorderLayout());
        header.setBackground(new java.awt.Color(80, 45, 15));
        header.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 18, 10, 18));

        javax.swing.JLabel titleLbl = new javax.swing.JLabel("  👑  Admin Dashboard  —  Hotel Royal");
        titleLbl.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
        titleLbl.setForeground(java.awt.Color.WHITE);

        javax.swing.JPanel userPanel = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 0));
        userPanel.setBackground(new java.awt.Color(80, 45, 15));

        String name = (Session.getCurrentUser() != null)
            ? Session.getCurrentUser().getName() : "Admin";

        javax.swing.JLabel nameLbl = new javax.swing.JLabel("👤  " + name);
        nameLbl.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        nameLbl.setForeground(java.awt.Color.WHITE);

        javax.swing.JLabel roleLbl = new javax.swing.JLabel("  ADMIN  ");
        roleLbl.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 11));
        roleLbl.setForeground(java.awt.Color.WHITE);
        roleLbl.setOpaque(true);
        roleLbl.setBackground(new java.awt.Color(198, 40, 40));
        roleLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 8, 3, 8));

        userPanel.add(nameLbl);
        userPanel.add(roleLbl);

        header.add(titleLbl,  java.awt.BorderLayout.WEST);
        header.add(userPanel, java.awt.BorderLayout.EAST);

        // Replace content pane with a BorderLayout wrapper
        javax.swing.JPanel root = new javax.swing.JPanel(new java.awt.BorderLayout());
        root.add(header,       java.awt.BorderLayout.NORTH);
        root.add(jTabbedPane1, java.awt.BorderLayout.CENTER);
        setContentPane(root);
    }

    private void onRoomNumChanged() {
        if (!suppressRoomNumListener) {
            editingExisting = false;
            editingRoomId   = -1;
            AddRoom.setText("Add Room");
        }
    }

    private void openRoomPicker() {
        java.awt.Frame frame = (java.awt.Frame)
            javax.swing.SwingUtilities.getWindowAncestor(this);
        RoomPickerDialog dlg = new RoomPickerDialog(frame, false);
        dlg.setVisible(true);
        Room r = dlg.getSelectedRoom();
        if (r != null) {
            suppressRoomNumListener = true;
            RoomNumber.setText(r.getRoomNumber());
            suppressRoomNumListener = false;
            cmbRoomType.setSelectedItem(r.getType());
            price1.setText(String.valueOf((int) r.getPrice()));
            cmbAvailable.setSelectedItem(r.isAvailable() ? "Yes" : "No");
            editingExisting = true;
            editingRoomId   = r.getRoomId();
            AddRoom.setText("Update Room");
        }
    }

    private void styleTextField(javax.swing.JTextField field) {
        field.setBackground(java.awt.Color.WHITE);
        field.setForeground(new java.awt.Color(30, 30, 30));
        field.setFont(new java.awt.Font("Segoe UI", 0, 15));
        field.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(160, 115, 60), 1),
            javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8)
        ));
        field.setCaretColor(new java.awt.Color(100, 60, 20));
    }

    private void styleButton(javax.swing.JButton btn, java.awt.Color bg) {
        btn.setBackground(bg);
        btn.setForeground(java.awt.Color.WHITE);
        btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 15));
        btn.setFocusPainted(false);
        btn.setBorderPainted(false);
        btn.setOpaque(true);
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }

    private void styleTable(javax.swing.JTable table) {
        table.setRowHeight(35);
        table.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        table.setForeground(new java.awt.Color(50, 50, 50));
        table.setBackground(java.awt.Color.WHITE);
        table.setGridColor(new java.awt.Color(235, 235, 235));
        table.setSelectionBackground(new java.awt.Color(200, 160, 100));
        table.setSelectionForeground(java.awt.Color.WHITE);
        table.setShowVerticalLines(false);
        table.setShowHorizontalLines(true);
        table.setIntercellSpacing(new java.awt.Dimension(0, 0));

        // Center align all columns
        javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        javax.swing.table.JTableHeader h = table.getTableHeader();
        h.setBackground(new java.awt.Color(80, 45, 15));
        h.setForeground(java.awt.Color.WHITE);
        h.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        h.setPreferredSize(new java.awt.Dimension(0, 40));
        
        ((javax.swing.table.DefaultTableCellRenderer) h.getDefaultRenderer())
            .setHorizontalAlignment(javax.swing.JLabel.CENTER);
    }

    private void editSelectedBooking() {
        int row = viewTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this,
                "Please select a booking row to edit.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int bookingId = (Integer) viewTable.getValueAt(row, 0);
        String checkIn  = (String) viewTable.getValueAt(row, 4);
        String checkOut = (String) viewTable.getValueAt(row, 5);
        String status   = (String) viewTable.getValueAt(row, 8);

        javax.swing.JTextField fldIn  = new javax.swing.JTextField(checkIn,  12);
        javax.swing.JTextField fldOut = new javax.swing.JTextField(checkOut, 12);
        javax.swing.JComboBox<String> cmbStat =
            new javax.swing.JComboBox<>(new String[]{"Confirmed", "Pending", "Cancelled"});
        cmbStat.setSelectedItem(status);

        javax.swing.JPanel p = new javax.swing.JPanel(new java.awt.GridLayout(3, 2, 8, 8));
        p.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        p.add(new javax.swing.JLabel("Check-In (YYYY-MM-DD):")); p.add(fldIn);
        p.add(new javax.swing.JLabel("Check-Out (YYYY-MM-DD):")); p.add(fldOut);
        p.add(new javax.swing.JLabel("Status:")); p.add(cmbStat);

        int res = JOptionPane.showConfirmDialog(this, p,
            "Edit Booking #" + bookingId, JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (res == JOptionPane.OK_OPTION) {
            try {
                if (new BookingDAO().updateBooking(bookingId,
                        fldIn.getText().trim(), fldOut.getText().trim(),
                        cmbStat.getSelectedItem().toString())) {
                    JOptionPane.showMessageDialog(this,
                        "Booking #" + bookingId + " updated.", "Success", JOptionPane.INFORMATION_MESSAGE);
                    showBtnActionPerformed(null);
                } else {
                    JOptionPane.showMessageDialog(this,
                        "Failed to update booking.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void cancelSelectedBooking() {
        int row = viewTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this,
                "Please select a booking row to cancel.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int bookingId = (Integer) viewTable.getValueAt(row, 0);
        int roomId    = (Integer) viewTable.getValueAt(row, 9);
        String status = (String)  viewTable.getValueAt(row, 8);

        if ("Cancelled".equals(status)) {
            JOptionPane.showMessageDialog(this,
                "Booking #" + bookingId + " is already cancelled.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
            "Cancel booking #" + bookingId + "? The room will be marked available.",
            "Confirm Cancel", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                if (new BookingDAO().cancelBooking(bookingId, roomId)) {
                    JOptionPane.showMessageDialog(this,
                        "Booking #" + bookingId + " cancelled.", "Success", JOptionPane.INFORMATION_MESSAGE);
                    showBtnActionPerformed(null);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void deleteSelectedBooking() {
        int row = viewTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this,
                "Please select a booking row to delete.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int bookingId = (Integer) viewTable.getValueAt(row, 0);
        int roomId    = (Integer) viewTable.getValueAt(row, 9);

        int confirm = JOptionPane.showConfirmDialog(this,
            "Permanently delete booking #" + bookingId + "? This cannot be undone.",
            "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                if (new BookingDAO().deleteBooking(bookingId, roomId)) {
                    JOptionPane.showMessageDialog(this,
                        "Booking #" + bookingId + " deleted.", "Success", JOptionPane.INFORMATION_MESSAGE);
                    showBtnActionPerformed(null);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void printSelectedInvoice() {
        int row = viewTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Please select a booking row to print.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int bookingId = (Integer) viewTable.getValueAt(row, 0);
        String customerName = (String) viewTable.getValueAt(row, 1);
        String roomNo = String.valueOf(viewTable.getValueAt(row, 2));
        String type = (String) viewTable.getValueAt(row, 3);
        String checkIn = (String) viewTable.getValueAt(row, 4);
        String checkOut = (String) viewTable.getValueAt(row, 5);
        String nights = String.valueOf(viewTable.getValueAt(row, 6));
        String amount = String.valueOf(viewTable.getValueAt(row, 7));
        String status = (String) viewTable.getValueAt(row, 8);
        
        String pdfPath = hotel.utils.PDFGenerator.generateInvoice(
            bookingId, customerName, roomNo, type, checkIn, checkOut, nights, amount, status
        );
        
        if (pdfPath != null) {
            try {
                java.awt.Desktop.getDesktop().open(new java.io.File(pdfPath));
            } catch (Exception ex) {
                // If opening fails, just show the path
            }
            JOptionPane.showMessageDialog(this, "Invoice generated successfully!\nSaved at: " + new java.io.File(pdfPath).getAbsolutePath(), "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Failed to generate invoice.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void setupStatisticsTab() {
        jPanel3.removeAll();
        jPanel3.setLayout(new java.awt.BorderLayout(20, 20));
        jPanel3.setBackground(new java.awt.Color(245, 238, 228));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));

        // Title
        javax.swing.JLabel title = new javax.swing.JLabel("Hotel Statistics Dashboard");
        title.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 28));
        title.setForeground(new java.awt.Color(60, 35, 10));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(title, java.awt.BorderLayout.NORTH);

        // Stat value labels
        statTotalRooms  = makeStatValueLabel();
        statAvailable   = makeStatValueLabel();
        statBooked      = makeStatValueLabel();
        statBookings    = makeStatValueLabel();
        statRevenue     = makeStatValueLabel();
        statCustomers   = makeStatValueLabel();

        // Stats Grid
        javax.swing.JPanel gridPanel = new javax.swing.JPanel(new java.awt.GridLayout(2, 3, 20, 20));
        gridPanel.setBackground(new java.awt.Color(245, 238, 228));
        gridPanel.add(makeStatCard("Total Rooms",    statTotalRooms,  new java.awt.Color(25, 118, 210)));
        gridPanel.add(makeStatCard("Available",      statAvailable,   new java.awt.Color(46, 125, 50)));
        gridPanel.add(makeStatCard("Booked",         statBooked,      new java.awt.Color(198, 40, 40)));
        gridPanel.add(makeStatCard("Total Bookings", statBookings,    new java.awt.Color(123, 31, 162)));
        gridPanel.add(makeStatCard("Revenue ($)",    statRevenue,     new java.awt.Color(230, 130, 20)));
        gridPanel.add(makeStatCard("Customers",      statCustomers,   new java.awt.Color(0, 121, 107)));
        jPanel3.add(gridPanel, java.awt.BorderLayout.CENTER);

        // Refresh button at the bottom
        javax.swing.JButton refreshBtn = new javax.swing.JButton("Refresh Statistics");
        styleButton(refreshBtn, new java.awt.Color(80, 45, 15));
        javax.swing.JPanel bottomPanel = new javax.swing.JPanel();
        bottomPanel.setBackground(new java.awt.Color(245, 238, 228));
        bottomPanel.add(refreshBtn);
        jPanel3.add(bottomPanel, java.awt.BorderLayout.SOUTH);
        refreshBtn.addActionListener(e -> loadStatistics());

        // Auto-load when Statistics tab is opened
        jTabbedPane1.addChangeListener(e -> {
            if (jTabbedPane1.getSelectedIndex() == 2) loadStatistics();
        });

        jPanel3.revalidate();
        jPanel3.repaint();
    }

    private javax.swing.JLabel makeStatValueLabel() {
        javax.swing.JLabel l = new javax.swing.JLabel("—");
        l.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 34));
        l.setForeground(java.awt.Color.WHITE);
        l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        return l;
    }

    private javax.swing.JPanel makeStatCard(String title,
                                             javax.swing.JLabel valueLbl,
                                             java.awt.Color bg) {
        javax.swing.JPanel card = new javax.swing.JPanel(new java.awt.BorderLayout(0, 4));
        card.setBackground(bg);
        card.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(bg.darker(), 2),
            javax.swing.BorderFactory.createEmptyBorder(10, 8, 10, 8)
        ));
        javax.swing.JLabel titleLbl = new javax.swing.JLabel(title);
        titleLbl.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
        titleLbl.setForeground(new java.awt.Color(220, 220, 220));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        card.add(titleLbl,  java.awt.BorderLayout.NORTH);
        card.add(valueLbl,  java.awt.BorderLayout.CENTER);
        return card;
    }

    private void loadStatistics() {
        new javax.swing.SwingWorker<java.util.Map<String, String>, Void>() {
            @Override
            protected java.util.Map<String, String> doInBackground() throws Exception {
                java.util.Map<String, String> stats = new java.util.HashMap<>();
                double revenue = new BookingDAO().calculateRevenue();
                stats.put("revenue", String.format("$%.0f", revenue));

                try (java.sql.Connection conn = hotel.database.DatabaseConnection.getConnection()) {
                    int totalRooms  = queryInt(conn, "SELECT COUNT(*) FROM rooms");
                    int bookedRooms = queryInt(conn,
                        "SELECT COUNT(DISTINCT room_id) FROM bookings WHERE status IN ('Confirmed','CheckedIn')");
                    stats.put("totalRooms", String.valueOf(totalRooms));
                    stats.put("availableRooms", String.valueOf(totalRooms - bookedRooms));
                    stats.put("bookedRooms", String.valueOf(bookedRooms));
                    stats.put("totalBookings", String.valueOf(queryInt(conn, "SELECT COUNT(*) FROM bookings")));
                    stats.put("customers", String.valueOf(queryInt(conn, "SELECT COUNT(*) FROM users WHERE role='customer'")));
                }
                return stats;
            }
            @Override
            protected void done() {
                try {
                    java.util.Map<String, String> stats = get();
                    statTotalRooms.setText(stats.get("totalRooms"));
                    statAvailable.setText(stats.get("availableRooms"));
                    statBooked.setText(stats.get("bookedRooms"));
                    statBookings.setText(stats.get("totalBookings"));
                    statRevenue.setText(stats.get("revenue"));
                    statCustomers.setText(stats.get("customers"));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(admin_dashboard.this,
                        "Error loading statistics: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }.execute();
    }

    private int queryInt(java.sql.Connection conn, String sql) throws java.sql.SQLException {
        try (java.sql.Statement st = conn.createStatement();
             java.sql.ResultSet rs = st.executeQuery(sql)) {
            return rs.next() ? rs.getInt(1) : 0;
        }
    }

    private double queryDouble(java.sql.Connection conn, String sql) throws java.sql.SQLException {
        try (java.sql.Statement st = conn.createStatement();
             java.sql.ResultSet rs = st.executeQuery(sql)) {
            return rs.next() ? rs.getDouble(1) : 0.0;
        }
    }

    private long calcNights(String checkIn, String checkOut) {
        try {
            java.time.LocalDate ci = parseDate(checkIn);
            java.time.LocalDate co = parseDate(checkOut);
            if (ci == null || co == null) return 0;
            long n = java.time.temporal.ChronoUnit.DAYS.between(ci, co);
            return n > 0 ? n : 0;
        } catch (Exception e) {
            return 0;
        }
    }

    private java.time.LocalDate parseDate(String d) {
        if (d == null || d.isBlank()) return null;
        d = d.trim();
        for (String pat : new String[]{"yyyy-MM-dd", "dd/MM/yyyy", "MM/dd/yyyy", "dd-MM-yyyy"}) {
            try {
                return java.time.LocalDate.parse(d,
                    java.time.format.DateTimeFormatter.ofPattern(pat));
            } catch (Exception ignored) {}
        }
        return null;
    }

    private void loadRooms() {
        new javax.swing.SwingWorker<java.util.List<hotel.model.Room>, Void>() {
            @Override
            protected java.util.List<hotel.model.Room> doInBackground() throws Exception {
                return new RoomDAO().getAllRooms();
            }
            @Override
            protected void done() {
                try {
                    java.util.List<hotel.model.Room> rooms = get();
                    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblRooms.getModel();
                    model.setRowCount(0);
                    for (hotel.model.Room r : rooms) {
                        model.addRow(new Object[]{r.getRoomNumber(), r.getType(), r.getPrice()});
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(admin_dashboard.this,
                        "Error loading rooms: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }.execute();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRoom;
    private javax.swing.JButton Back;
    private javax.swing.JButton Back1;
    private javax.swing.JTextField RoomNumber;
    private javax.swing.JComboBox<String> cmbRoomType;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextField isAvalibleTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField price1;
    private javax.swing.JButton quit;
    private javax.swing.JButton showBtn;
    private javax.swing.JTable tblRooms;
    private javax.swing.JTable viewTable;
    // End of variables declaration//GEN-END:variables
}
