/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelbookingsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Hanin
 */
public class IndexPage extends javax.swing.JFrame {

    /**
     * Creates new form IndexPage
     */
    public IndexPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        logBtn_Page = new javax.swing.JButton();
        registerBtn_Page = new javax.swing.JButton();
        exit_indexPage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logBtn_Page.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        logBtn_Page.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelbookingsystem/icons8-login-32.png"))); // NOI18N
        logBtn_Page.setText("Login");
        logBtn_Page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logBtn_PageActionPerformed(evt);
            }
        });
        jPanel2.add(logBtn_Page, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 103, 190, 56));

        registerBtn_Page.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        registerBtn_Page.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelbookingsystem/icons8-add-user-male-50.png"))); // NOI18N
        registerBtn_Page.setText("Register");
        registerBtn_Page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtn_PageActionPerformed(evt);
            }
        });
        jPanel2.add(registerBtn_Page, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 188, 190, 54));

        exit_indexPage.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        exit_indexPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelbookingsystem/icons8-exit-48.png"))); // NOI18N
        exit_indexPage.setText("Exit");
        exit_indexPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_indexPageActionPerformed(evt);
            }
        });
        jPanel2.add(exit_indexPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 260, 190, 52));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hotel Booking System");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 29, 380, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelbookingsystem/WhatsApp Image 2026-05-05 at 7.59.37 PM.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 390));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logBtn_PageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logBtn_PageActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_logBtn_PageActionPerformed

    private void registerBtn_PageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtn_PageActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new RegistPage().setVisible(true);
    }//GEN-LAST:event_registerBtn_PageActionPerformed

    private void exit_indexPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_indexPageActionPerformed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(null, "Do You Really Want to Exit",
                 "Select", JOptionPane.YES_NO_OPTION);

        if (exit == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_exit_indexPageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndexPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndexPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndexPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndexPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndexPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit_indexPage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logBtn_Page;
    private javax.swing.JButton registerBtn_Page;
    // End of variables declaration//GEN-END:variables
}
