/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelbookingsystem;

import javax.swing.JOptionPane;
import hotel.model.*;
import hotel.dao.UserDAO;

/**
 *
 * @author Hanin
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form HotelSystem
     */
    public LoginPage() {
        initComponents();
        customizeUI();
    }

    private void customizeUI() {
        java.awt.Color white = java.awt.Color.WHITE;

        // Title - large white bold
        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 32));
        jLabel1.setForeground(white);

        // Field labels - white bold, visible on wood
        java.awt.Font lblFont = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 17);
        jLabel2.setFont(lblFont); jLabel2.setForeground(white);
        jLabel3.setFont(lblFont); jLabel3.setForeground(white);

        // Text fields
        styleField(Username_login);

        // Password field
        password_login.setBackground(java.awt.Color.WHITE);
        password_login.setForeground(new java.awt.Color(30, 30, 30));
        password_login.setFont(new java.awt.Font("Segoe UI", 0, 18));
        password_login.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(160, 115, 60), 1),
            javax.swing.BorderFactory.createEmptyBorder(4, 10, 4, 10)
        ));
        password_login.setCaretColor(new java.awt.Color(100, 60, 20));

        // Checkbox
        showPass.setForeground(white);
        showPass.setFont(new java.awt.Font("Segoe UI", 0, 14));
        showPass.setOpaque(false);

        // Buttons
        styleButton(Login_btn, new java.awt.Color(46, 125, 50));
        styleButton(back_btn,  new java.awt.Color(25, 118, 210));
    }

    private void styleField(javax.swing.JTextField f) {
        f.setBackground(java.awt.Color.WHITE);
        f.setForeground(new java.awt.Color(30, 30, 30));
        f.setFont(new java.awt.Font("Segoe UI", 0, 18));
        f.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(160, 115, 60), 1),
            javax.swing.BorderFactory.createEmptyBorder(4, 10, 4, 10)
        ));
        f.setCaretColor(new java.awt.Color(100, 60, 20));
    }

    private void styleButton(javax.swing.JButton btn, java.awt.Color bg) {
        btn.setBackground(bg);
        btn.setForeground(java.awt.Color.WHITE);
        btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
        btn.setFocusPainted(false);
        btn.setBorderPainted(false);
        btn.setOpaque(true);
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomPage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Username_login = new javax.swing.JTextField();
        Login_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        password_login = new javax.swing.JPasswordField();
        showPass = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(243, 244, 246));
        setForeground(java.awt.Color.lightGray);

        WelcomPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome");
        WelcomPage.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 11, 241, 73));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Username");
        WelcomPage.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 115, 134, 42));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Password :");
        WelcomPage.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 134, 42));

        Username_login.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        WelcomPage.add(Username_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 115, 301, 42));

        Login_btn.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Login_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelbookingsystem/icons8-login-32.png"))); // NOI18N
        Login_btn.setText("Login");
        Login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_btnActionPerformed(evt);
            }
        });
        WelcomPage.add(Login_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 296, 153, 48));

        back_btn.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelbookingsystem/icons8-go-back-24.png"))); // NOI18N
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        WelcomPage.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 362, 153, 48));

        password_login.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        WelcomPage.add(password_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 200, 301, 42));

        showPass.setText("Show Password");
        showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassActionPerformed(evt);
            }
        });
        WelcomPage.add(showPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 255, 153, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelbookingsystem/WhatsApp Image 2026-05-05 at 7.59.37 PM.jpeg"))); // NOI18N
        jLabel4.setText("jLabel4");
        WelcomPage.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WelcomPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WelcomPage, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new IndexPage().setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    private void Login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_btnActionPerformed
        String email = Username_login.getText().trim();
        String pass  = new String(password_login.getPassword()).trim();

        if (email.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please enter your email and password.",
                "Missing Fields", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            UserDAO userDAO = new UserDAO();
            User user = userDAO.loginUser(email, pass);

            if (user != null) {
                Session.setCurrentUser(user);
                setVisible(false);
                if (user instanceof Admin) {
                    new admin_dashboard().setVisible(true);
                } else if (user instanceof hotel.model.Receptionist) {
                    new Receptionist_Dashboard().setVisible(true);
                } else {
                    new Custmor_Dashboard().setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                    "<html><b style='color:red'>Incorrect email or password.<br>Please try again.</b></html>",
                    "Login Failed", JOptionPane.ERROR_MESSAGE);
                password_login.setText("");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Database connection error.\nPlease make sure MySQL is running.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Login_btnActionPerformed

    private void showPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassActionPerformed
        // TODO add your handling code here:

        if (showPass.isSelected()) {
            password_login.setEchoChar((char) 0);
        } else {
            password_login.setEchoChar('*');
        }
    }//GEN-LAST:event_showPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login_btn;
    private javax.swing.JTextField Username_login;
    private javax.swing.JPanel WelcomPage;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField password_login;
    private javax.swing.JCheckBox showPass;
    // End of variables declaration//GEN-END:variables
}
